// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wiley.Apartments.Web.Data;

#nullable disable

namespace Wiley.Apartments.Web.Data.Migrations
{
    [DbContext(typeof(ApartmentsDbContext))]
    [Migration("20260810154000_AddUnitIsFacility")]
    partial class AddUnitIsFacility
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Snapshot is maintained in ApartmentsDbContextModelSnapshot.cs
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0");
#pragma warning restore 612, 618
        }
    }
}
